### ISSUE TITLE
Need help with mutation query 

### ISSUE THREAD

**Issue by Unic-X** [Unic-X/Anlist-Post-Ext#1]
## Mutation wtf

https://github.com/Unic-X/Anlist-Post-Ext/blob/2afddf1534ebaffeae71d734be6f3974ff3b4c40/schema.gql#L8-L13

Is there anyway to get the id and resolve the same in the query like any way to get the ID from the media query below and give the same id to Mutation without ever returning to client 
https://github.com/Unic-X/Anlist-Post-Ext/blob/2afddf1534ebaffeae71d734be6f3974ff3b4c40/schema.gql#L1-L7

**Comment by archit-spec** [comment]
acca

**Comment by Unic-X** [comment]
kab hoga 😢

**Comment by archit-spec** [comment]
man 😭 try kar raha hu

**Comment by archit-spec** [comment]
time waste kar raha tha tab se 😭

**Comment by Unic-X** [comment]
Mera chehra when thanks yaar thanks yaar thanks yaar

**Comment by natto1784** [comment]
momento

**Comment by Unic-X** [comment]
Can't be helped u always have to get the I'd of anime and return it back for mutation purpose
