### ISSUE TITLE
Nice songs nice songs nice songs

### ISSUE THREAD

**Issue by Unic-X** [Unic-X/Anlist-Post-Ext#4]
@archit-spec ise sun poggers hai

[![Everything Is AWESOME](https://yt-embed.herokuapp.com/embed?v=E6Vn17S37_Y)](https://www.youtube.com/watch?v=E6Vn17S37_Y "Hi")
[![Everything Is AWESOME](https://yt-embed.herokuapp.com/embed?v=w4RvskuFnPY)](https://www.youtube.com/watch?v=w4RvskuFnPY "Hi")
[![Everything Is AWESOME](https://yt-embed.herokuapp.com/embed?v=MRb1-SAAIzs)](https://www.youtube.com/watch?v=MRb1-SAAIzs "Hi")
[![Everything Is AWESOME](https://yt-embed.herokuapp.com/embed?v=1fgnEDi7bq0)](https://www.youtube.com/watch?v=1fgnEDi7bq0 "Hi")
[![Everything Is AWESOME](https://yt-embed.herokuapp.com/embed?v=V1bFr2SWP1I)](https://www.youtube.com/watch?v=V1bFr2SWP1I "Hi")

**Comment by archit-spec** [comment]
acha

**Comment by archit-spec** [comment]
ye issue kaise resolve karu

**Comment by Unic-X** [comment]
> ye issue kaise resolve karu  😰
😰 Sua imposter amogus
